CREATE TABLE
  IF NOT EXISTS public.commissions (
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    oid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status text NOT NULL DEFAULT 'in_setup'::text,
    public_note text NULL,
    secure_note text NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NULL,
    customer uuid NOT NULL,
    CONSTRAINT commissions_pkey PRIMARY KEY (id),
    CONSTRAINT commissions_id_key UNIQUE (id),
    CONSTRAINT commissions_oid_key UNIQUE (oid),
    CONSTRAINT commissions_customer_fkey FOREIGN KEY (customer) REFERENCES public.customers (id)
  )
WITH
  (OIDS = FALSE);

ALTER TABLE public.commissions ENABLE ROW LEVEL SECURITY;

CREATE TABLE
  IF NOT EXISTS public.commissions_bases (
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    creator_name text NOT NULL,
    storefront_url text NOT NULL,
    CONSTRAINT commissions_bases_pkey PRIMARY KEY (id),
    CONSTRAINT commissions_bases_name_key UNIQUE (name)
  )
WITH
  (OIDS = FALSE);

ALTER TABLE public.commissions_bases ENABLE ROW LEVEL SECURITY;

CREATE TABLE
  IF NOT EXISTS public.commissions_characters (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NOT NULL,
    commission uuid NOT NULL,
    note text NULL,
    changelog json NOT NULL DEFAULT '[]'::json,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    base uuid NOT NULL,
    order_id text NULL,
    CONSTRAINT commissions_characters_pkey PRIMARY KEY (id, base, commission),
    CONSTRAINT commissions_characters_order_id_key UNIQUE (order_id),
    CONSTRAINT commissions_characters_base_fkey FOREIGN KEY (base) REFERENCES public.commissions_bases (id),
    CONSTRAINT commissions_characters_commission_fkey FOREIGN KEY (commission) REFERENCES public.commissions (id)
  )
WITH
  (OIDS = FALSE);

ALTER TABLE public.commissions_characters ENABLE ROW LEVEL SECURITY;

CREATE TABLE
  IF NOT EXISTS public.commissions_payments (
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    commission uuid NOT NULL,
    currency text NOT NULL,
    income_amount real NOT NULL DEFAULT '0'::real,
    state text NOT NULL,
    public_note text NULL,
    secure_note text NULL,
    pid uuid NOT NULL DEFAULT gen_random_uuid (),
    payment_ext_id text NOT NULL,
    payment_ext_url text NOT NULL,
    payment_processor text NOT NULL,
    CONSTRAINT commissions_payments_pkey PRIMARY KEY (pid, commission),
    CONSTRAINT commissions_payments_pid_key UNIQUE (pid),
    CONSTRAINT commissions_payments_commission_fkey FOREIGN KEY (commission) REFERENCES public.commissions (id)
  )
WITH
  (OIDS = FALSE);

ALTER TABLE public.commissions_payments ENABLE ROW LEVEL SECURITY;